### ISSUE TITLE
October 2018 Update (17763) DataGrid Issue

### ISSUE THREAD

**Issue by LanceMcCarthy** [telerik/UI-For-UWP#324]
Reported issue after updating target SDK to 17763:

https://www.telerik.com/forums/raddatagrid-does-not-work-after-update-win-10-to-1809-(17763)

### Code Reproduce:

```xml
<Page
    x:Class="Test02.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:grid="using:Telerik.UI.Xaml.Controls.Grid"
    mc:Ignorable="d">
    <Grid>
        <grid:RadDataGrid></grid:RadDataGrid>
    </Grid>
</Page>
```

### Steps to Reproduce:

1 - Change target SDK version to **17763** and set Min SDK to **16299**
2 - Rebuild

### Expected Result

Successful compilation and deployment

### Current Result:

Compilation error
```
Cannot deserialize XBF metadata type list as 'RadDataGrid' was not found in namespace 'Telerik.UI.Xaml.Controls.Grid'. [Line: 0 Position: 0]
```

**Comment by LanceMcCarthy** [comment]
I was able to reproduce this, and it appears to be an issue with Visual Studio. The fix is the following...

1 - Close Visual Studio, 
2 - Reopen the project in Visual Studio 
3 - **Rebuild** the project.

At this point the project will successfully build and deploy.

**Comment by LanceMcCarthy** [comment]
Correction. The exception is present after subsequent deployment.

**Comment by LanceMcCarthy** [comment]
Follow up: After changing Min SDK from 16299 to 10240, the exception no longer occurs.

**Comment by IstvanKor** [comment]
Also the exception disappears when min version targeted to 10586. It appears the exception occurs in case of min version 14393 or higher.

**Comment by APopatanasov** [comment]
@IstvanKor We have some insight about the cause of the issue and I hope we will be able to fix it soon.  

The issue is caused by the PropertyMetadata of the **ExternalEditorProperty** and by the fact that a new instance is created inside it as a default value. That makes the xaml parser to register the "Telerik.UI.Xaml.Controls.Grid.RadDataGrid" twice and because of that  **"System.ArgumentException: 'An item with the same key has already been added. Key: Telerik.UI.Xaml.Controls.Grid.RadDataGrid'"** which is actually the real exception. When the control is declared in code-behind the exception is not observed. 

Even though I can not 100% blame the DataGrid for the issue we will try to apply a fix in it, so it could work with the new SDK and probably we will reach Microsoft and ask them for some more input on the issue.
